"""DNS and Nginx routing service.

Manages Nginx upstream configuration for deployed apps under the
domain scheme:

    <deployid>-<username>.dev.sdc.cpp

Each deploy gets a unique hostname (single-level subdomain so that a
standard DNS wildcard *.dev.sdc.cpp resolves all deploy URLs).  Nginx
resolves these via per-deploy config files in conf.d/upstreams/ that
contain:
  1. An upstream block (e.g. upstream deploy_a1b2c3d4 { server 10.128.30.80:3000; })
  2. A server block with an exact server_name matching the deploy hostname

The main nginx.conf also has a *-*.dev.sdc.cpp wildcard catch-all for
deploys whose config has not yet been written.

Nginx reload is signaled by writing a flag file to a shared volume.
The nginx entrypoint script polls this file every 2 seconds, validates
the config with nginx -t, and runs nginx -s reload when a change is
detected.
"""

import asyncio
import logging
from pathlib import Path
from textwrap import dedent

from app.config import settings
from app.utils.dns import deploy_hostname, production_hostname, sanitize_username

logger = logging.getLogger(__name__)

# Directories
UPSTREAM_DIR = Path(settings.nginx_upstream_dir)
RELOAD_FLAG_DIR = Path(settings.nginx_reload_flag_dir)

# ---------------------------------------------------------------------------
# Per-project locks — prevent concurrent production URL writes for the
# same project from racing each other (older deploy overwriting newer).
# ---------------------------------------------------------------------------

_production_locks: dict[str, asyncio.Lock] = {}


def _get_production_lock(project_slug: str) -> asyncio.Lock:
    """Return (or create) the asyncio.Lock for a project's production routing."""
    if project_slug not in _production_locks:
        _production_locks[project_slug] = asyncio.Lock()
    return _production_locks[project_slug]

# ---------------------------------------------------------------------------
# Nginx config templates
# ---------------------------------------------------------------------------

UPSTREAM_TEMPLATE = dedent("""\
    # Auto-generated by TBD Platform
    # Deploy ID: {deploy_id}
    # Hostname:  {hostname}
    # Generated: {timestamp}

    upstream {upstream_name} {{
        server {backend_ip}:{backend_port};
    }}
""")

SERVER_TEMPLATE = dedent("""\
    # {hostname} -> {backend_ip}:{backend_port}
    server {{
        listen 443 ssl;
        server_name {hostname};

        ssl_certificate     /etc/nginx/ssl/tbd.crt;
        ssl_certificate_key /etc/nginx/ssl/tbd.key;

        location / {{
            proxy_pass http://{upstream_name};
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }}

        location /health {{
            proxy_pass http://{upstream_name}/health;
        }}
    }}
""")


class DNSRoutingError(Exception):
    """Raised when DNS/Nginx routing update fails."""
    pass


def _strip_cidr(ip_with_cidr: str) -> str:
    """Strip CIDR notation from an IP address (172.16.1.10/25 -> 172.16.1.10)."""
    return ip_with_cidr.split("/")[0] if "/" in ip_with_cidr else ip_with_cidr


def _make_upstream_name(deploy_id: str) -> str:
    """Generate a safe Nginx upstream name from a deploy ID.

    Example: 'a1b2c3d4-...' -> 'deploy_a1b2c3d4'
    """
    short = deploy_id.replace("-", "")[:8]
    return f"deploy_{short}"


def generate_upstream_config(
    deploy_id: str,
    owner_username: str,
    backend_ip: str,
    backend_port: int,
) -> str:
    """Generate the full Nginx config (upstream + server block) for a deploy.

    Args:
        deploy_id: Full deploy UUID string.
        owner_username: Project owner's AD username (will be sanitized).
        backend_ip: LXC container IP (CIDR stripped automatically).
        backend_port: Application port.

    Returns:
        Complete Nginx config fragment.
    """
    import uuid
    from datetime import datetime, timezone

    backend_ip = _strip_cidr(backend_ip)
    upstream_name = _make_upstream_name(deploy_id)
    hostname = deploy_hostname(uuid.UUID(deploy_id), owner_username)
    timestamp = datetime.now(timezone.utc).isoformat()

    config = UPSTREAM_TEMPLATE.format(
        deploy_id=deploy_id,
        hostname=hostname,
        timestamp=timestamp,
        upstream_name=upstream_name,
        backend_ip=backend_ip,
        backend_port=backend_port,
    )

    config += "\n" + SERVER_TEMPLATE.format(
        hostname=hostname,
        upstream_name=upstream_name,
        backend_ip=backend_ip,
        backend_port=backend_port,
    )

    return config


async def write_upstream_config(
    deploy_id: str,
    owner_username: str,
    backend_ip: str,
    backend_port: int,
) -> Path:
    """Generate and write an Nginx upstream config file for a deploy.

    Writes to: {nginx_upstream_dir}/deploy-{short_id}.conf

    Returns:
        Path to the written config file.
    """
    import uuid

    UPSTREAM_DIR.mkdir(parents=True, exist_ok=True)

    config_content = generate_upstream_config(
        deploy_id=deploy_id,
        owner_username=owner_username,
        backend_ip=backend_ip,
        backend_port=backend_port,
    )

    short_id = deploy_id.replace("-", "")[:8]
    filename = f"deploy-{short_id}.conf"
    config_path = UPSTREAM_DIR / filename
    config_path.write_text(config_content)

    hostname = deploy_hostname(uuid.UUID(deploy_id), owner_username)
    logger.info(
        "Wrote Nginx upstream config: %s (%s -> %s:%d)",
        config_path, hostname, _strip_cidr(backend_ip), backend_port,
    )

    return config_path


async def remove_upstream_config(deploy_id: str) -> bool:
    """Remove an Nginx upstream config file for a deploy.

    Called when a deploy is deactivated or a preview environment is cleaned up.

    Returns True if a file was removed, False if it didn't exist.
    """
    short_id = deploy_id.replace("-", "")[:8]
    filename = f"deploy-{short_id}.conf"
    config_path = UPSTREAM_DIR / filename

    if config_path.exists():
        config_path.unlink()
        logger.info("Removed Nginx upstream config: %s", config_path)
        return True

    return False


async def signal_nginx_reload() -> bool:
    """Signal the Nginx container to reload its configuration.

    Instead of running 'nginx -s reload' (which only works inside the nginx
    container), we write a timestamp to a flag file on a shared volume.  The
    nginx container watches this via inotifywait and reloads when the file
    changes.

    Returns True on success.
    """
    try:
        RELOAD_FLAG_DIR.mkdir(parents=True, exist_ok=True)
        flag_path = RELOAD_FLAG_DIR / "reload"

        from datetime import datetime, timezone
        flag_path.write_text(datetime.now(timezone.utc).isoformat())

        logger.info("Nginx reload signaled via %s", flag_path)
        return True
    except Exception as e:
        logger.error("Failed to signal Nginx reload: %s", e)
        raise DNSRoutingError(f"Failed to signal Nginx reload: {e}")


async def register_deploy_routing(
    deploy_id: str,
    owner_username: str,
    backend_ip: str,
    backend_port: int,
) -> Path:
    """Full DNS registration: write config + signal Nginx reload.

    This is the main entry point called by the deploy executor when a
    deploy transitions to 'active'.

    Args:
        deploy_id: Full deploy UUID string.
        owner_username: Project owner's AD username.
        backend_ip: LXC container IP.
        backend_port: Application port.

    Returns:
        Path to the written config file.

    Raises:
        DNSRoutingError: If config write or reload fails.
    """
    config_path = await write_upstream_config(
        deploy_id=deploy_id,
        owner_username=owner_username,
        backend_ip=backend_ip,
        backend_port=backend_port,
    )

    await signal_nginx_reload()

    logger.info(
        "DNS routing registered for deploy %s -> %s:%d",
        deploy_id, _strip_cidr(backend_ip), backend_port,
    )

    return config_path


async def unregister_deploy_routing(deploy_id: str) -> bool:
    """Remove DNS routing for a deploy and signal Nginx reload.

    Called when a deploy is deactivated or a preview environment is destroyed.
    """
    removed = await remove_upstream_config(deploy_id)
    if removed:
        try:
            await signal_nginx_reload()
        except DNSRoutingError:
            logger.error(
                "Failed to signal Nginx reload after removing deploy %s config",
                deploy_id,
            )
    return removed


# ---------------------------------------------------------------------------
# Persistent production URL routing
# ---------------------------------------------------------------------------

PRODUCTION_UPSTREAM_TEMPLATE = dedent("""\
    # Auto-generated by TBD Platform — Persistent Production URL
    # Project: {project_slug}
    # Hostname: {hostname}
    # Backed by deploy: {deploy_id}
    # Generated: {timestamp}

    upstream {upstream_name} {{
        server {backend_ip}:{backend_port};
    }}
""")

PRODUCTION_SERVER_TEMPLATE = dedent("""\
    # {hostname} -> {backend_ip}:{backend_port} (production alias)
    server {{
        listen 443 ssl;
        server_name {hostname};

        ssl_certificate     /etc/nginx/ssl/tbd.crt;
        ssl_certificate_key /etc/nginx/ssl/tbd.key;

        location / {{
            proxy_pass http://{upstream_name};
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }}

        location /health {{
            proxy_pass http://{upstream_name}/health;
        }}
    }}
""")


def _make_production_upstream_name(project_slug: str) -> str:
    """Generate a safe Nginx upstream name for a production alias.

    Example: 'my-app' -> 'prod_my_app'
    """
    safe = project_slug.replace("-", "_")[:32]
    return f"prod_{safe}"


async def register_production_routing(
    project_slug: str,
    owner_username: str,
    backend_ip: str,
    backend_port: int,
    deploy_id: str = "",
) -> Path:
    """Write/overwrite the persistent production URL Nginx config.

    This is called every time a new deploy is promoted to active.
    It overwrites the previous config so the production hostname
    seamlessly switches to the new backend.

    Acquires a per-project lock so that two concurrent deploys for
    the same project cannot race — only one writes the config file
    at a time.

    Config file: {nginx_upstream_dir}/prod-{slug}.conf

    Returns:
        Path to the written config file.
    """
    from datetime import datetime, timezone

    lock = _get_production_lock(project_slug)
    async with lock:
        UPSTREAM_DIR.mkdir(parents=True, exist_ok=True)

        backend_ip = _strip_cidr(backend_ip)
        upstream_name = _make_production_upstream_name(project_slug)
        hostname = production_hostname(project_slug, owner_username)
        timestamp = datetime.now(timezone.utc).isoformat()

        config = PRODUCTION_UPSTREAM_TEMPLATE.format(
            project_slug=project_slug,
            hostname=hostname,
            deploy_id=deploy_id,
            timestamp=timestamp,
            upstream_name=upstream_name,
            backend_ip=backend_ip,
            backend_port=backend_port,
        )

        config += "\n" + PRODUCTION_SERVER_TEMPLATE.format(
            hostname=hostname,
            upstream_name=upstream_name,
            backend_ip=backend_ip,
            backend_port=backend_port,
        )

        filename = f"prod-{project_slug}.conf"
        config_path = UPSTREAM_DIR / filename
        config_path.write_text(config)

        logger.info(
            "Wrote production Nginx config: %s (%s -> %s:%d)",
            config_path, hostname, backend_ip, backend_port,
        )

        await signal_nginx_reload()
        return config_path


async def unregister_production_routing(project_slug: str) -> bool:
    """Remove the persistent production URL Nginx config.

    Called when a project is fully torn down (no active deploys remain).
    """
    filename = f"prod-{project_slug}.conf"
    config_path = UPSTREAM_DIR / filename

    if config_path.exists():
        config_path.unlink()
        logger.info("Removed production Nginx config: %s", config_path)
        try:
            await signal_nginx_reload()
        except DNSRoutingError:
            logger.error("Failed to signal Nginx reload after removing production config for %s", project_slug)
        return True

    return False
