"""Init script generator for LXC containers.

Generates a simple shell-based /sbin/init for LXC containers created
from Docker/OCI images.  Docker images typically have NO init system
(no systemd, no OpenRC) — so we inject a minimal init script that:

1. Mounts essential pseudo-filesystems (/proc, /sys, /dev/pts, /tmp)
2. Sets hostname
3. Brings up loopback and eth0 (DHCP or static from LXC config)
4. Sources /etc/tbd/secrets.env for injected secrets
5. Sets PORT, NODE_ENV, PATH environment variables
6. cd's to the workdir and exec's the app command as PID 1

Also creates /etc/tbd/ directory and empty secrets.env placeholder.

Replaces the previous systemd_generator.py — the dataclass and function
names are kept compatible so deploy_executor.py imports still work.
"""

import logging
from dataclasses import dataclass
from pathlib import Path
from textwrap import dedent

from app.services.oci_converter import OCIConfig

logger = logging.getLogger(__name__)


@dataclass
class SystemdUnitParams:
    """Parameters for init script generation.

    Name kept as SystemdUnitParams for backward compatibility with
    deploy_executor.py imports.
    """

    project_name: str
    project_slug: str
    env_name: str  # e.g. "production", "pr-5"
    env_type: str  # "production", "staging", "preview"
    oci_config: OCIConfig
    # Network config — needed because ostype=unmanaged means Proxmox
    # does NOT auto-configure the container's network interfaces.
    ip_address: str = ""  # e.g. "172.16.4.10/25" (CIDR notation)
    gateway: str = ""  # e.g. "172.16.4.1"


def _generate_init_script(params: SystemdUnitParams) -> str:
    """Generate a minimal /sbin/init shell script for the LXC container.

    This script becomes PID 1 inside the container. It sets up the bare
    minimum environment and then exec's the application process.
    """
    port = params.oci_config.primary_port
    exec_cmd = params.oci_config.exec_command
    workdir = params.oci_config.working_dir

    # Build environment variable exports from OCI config
    env_exports = []
    for key, value in params.oci_config.env.items():
        # Shell-escape single quotes in values
        safe_value = value.replace("'", "'\\''")
        env_exports.append(f"export {key}='{safe_value}'")

    env_block = "\n".join(env_exports) if env_exports else "# (no OCI env vars)"

    # Build the network config block
    if params.ip_address:
        net_block = dedent(f"""\
        # Bring up loopback
        ip link set lo up 2>/dev/null || true

        # Bring up eth0 and assign static IP
        # ostype=unmanaged means Proxmox does NOT configure networking for us
        ip link set eth0 up 2>/dev/null || true
        ip addr add {params.ip_address} dev eth0 2>/dev/null || true
        """)
        if params.gateway:
            net_block += f"ip route add default via {params.gateway} 2>/dev/null || true\n"
    else:
        net_block = dedent("""\
        # Bring up loopback
        ip link set lo up 2>/dev/null || true
        # Bring up eth0 — no static IP available, relying on LXC config
        ip link set eth0 up 2>/dev/null || true
        """)

    script = dedent(f"""\
        #!/bin/sh
        # TBD Platform — LXC init script
        # Project: {params.project_name} ({params.env_name})
        # Generated by TBD deploy pipeline — do not edit
        #
        # This script is PID 1 inside the LXC container.

        set -e

        # ── 1. Mount essential pseudo-filesystems ──────────────────────
        mount -t proc proc /proc 2>/dev/null || true
        mount -t sysfs sys /sys 2>/dev/null || true
        mount -t tmpfs tmpfs /tmp 2>/dev/null || true
        mount -t tmpfs tmpfs /run 2>/dev/null || true
        mkdir -p /dev/pts
        mount -t devpts devpts /dev/pts 2>/dev/null || true
        mkdir -p /dev/shm
        mount -t tmpfs tmpfs /dev/shm 2>/dev/null || true

        # ── 2. Hostname ────────────────────────────────────────────────
        hostname "{params.project_slug}-{params.env_name}" 2>/dev/null || true

        # ── 3. Networking ──────────────────────────────────────────────
        {net_block.strip()}

        # Set up DNS resolver if not present
        if [ ! -f /etc/resolv.conf ] || [ ! -s /etc/resolv.conf ]; then
            echo "nameserver 8.8.8.8" > /etc/resolv.conf
            echo "nameserver 1.1.1.1" >> /etc/resolv.conf
        fi

        # ── 4. Environment from OCI image ──────────────────────────────
        {env_block}

        # ── 5. TBD platform environment ────────────────────────────────
        export PORT='{port}'
        export NODE_ENV='{params.env_type}'
        export TBD_PROJECT='{params.project_slug}'
        export TBD_ENV='{params.env_name}'

        # Source injected secrets (written by secrets_injector)
        if [ -f /etc/tbd/secrets.env ]; then
            set -a
            . /etc/tbd/secrets.env
            set +a
        fi

        # ── 6. Ensure PATH includes common binary locations ────────────
        export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:${{PATH}}"

        # ── 7. Launch application ──────────────────────────────────────
        cd "{workdir}" || cd /

        echo "[tbd-init] Starting: {exec_cmd}"
        echo "[tbd-init] PORT=${{PORT}} NODE_ENV=${{NODE_ENV}} PWD=$(pwd)"

        # exec replaces this shell with the app process (becomes PID 1)
        exec {exec_cmd}
    """)

    return script


def install_unit_to_rootfs(
    rootfs_path: Path,
    params: SystemdUnitParams,
) -> Path:
    """Install the init script and supporting files into the unpacked rootfs.

    Replaces the previous systemd unit installation. Creates:
    - /sbin/init           — the main init script (PID 1)
    - /etc/tbd/secrets.env — placeholder for injected secrets

    Args:
        rootfs_path: Path to the unpacked rootfs directory (umoci output)
        params: Init script parameters

    Returns:
        Path to the installed init script
    """
    # umoci unpack nests the actual rootfs under rootfs_path/rootfs/
    actual_rootfs = rootfs_path / "rootfs"
    if not actual_rootfs.exists():
        actual_rootfs = rootfs_path

    # ── Create /etc/tbd/ and secrets.env ──────────────────────────
    tbd_etc_dir = actual_rootfs / "etc" / "tbd"
    tbd_etc_dir.mkdir(parents=True, exist_ok=True)

    secrets_env = tbd_etc_dir / "secrets.env"
    if not secrets_env.exists():
        secrets_env.write_text("# TBD Platform - injected secrets\n")

    # ── Generate and install /sbin/init ───────────────────────────
    sbin_dir = actual_rootfs / "sbin"
    sbin_dir.mkdir(parents=True, exist_ok=True)

    init_script = _generate_init_script(params)
    init_path = sbin_dir / "init"

    # Remove or back up existing /sbin/init.
    # Docker images often have /sbin/init as a symlink (e.g. -> /bin/busybox
    # or -> /lib/systemd/systemd).  Because the symlink target is an absolute
    # path, Path.exists() and Path.write_text() resolve it on the HOST, not
    # inside the rootfs — so we must unlink the symlink first.
    if init_path.is_symlink():
        target = init_path.readlink()
        logger.info("Removing /sbin/init symlink (target=%s)", target)
        init_path.unlink()
    elif init_path.exists():
        backup = sbin_dir / "init.original"
        if not backup.exists():
            init_path.rename(backup)
            logger.info("Backed up existing /sbin/init to /sbin/init.original")
        else:
            init_path.unlink()

    init_path.write_text(init_script)
    init_path.chmod(0o755)
    logger.info("Installed init script at %s", init_path)

    # ── Ensure /etc/passwd has root entry (some Docker images lack it) ─
    etc_dir = actual_rootfs / "etc"
    passwd_file = etc_dir / "passwd"
    if not passwd_file.exists():
        passwd_file.write_text("root:x:0:0:root:/root:/bin/sh\nnobody:x:65534:65534:nobody:/:/sbin/nologin\n")
        logger.info("Created minimal /etc/passwd")

    group_file = etc_dir / "group"
    if not group_file.exists():
        group_file.write_text("root:x:0:\nnogroup:x:65534:\n")
        logger.info("Created minimal /etc/group")

    logger.info(
        "Init script installed for %s/%s in rootfs %s (cmd=%s, port=%d)",
        params.project_slug,
        params.env_name,
        rootfs_path,
        params.oci_config.exec_command,
        params.oci_config.primary_port,
    )

    return init_path
